# Generated by Django 3.1.6 on 2021-02-21 21:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('complete', models.BooleanField()),
                ('brief', models.TextField()),
                ('image', models.ImageField(upload_to='designs/%Y/%m/%d/')),
                ('edits_remaining', models.IntegerField(default=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
